# Generated by Django 6.0.7 on 2026-07-29 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
